### ISSUE TITLE
现在还有维护？

### ISSUE THREAD

**Issue by testxin** [mtjs/mt#11]
发现下载后的demo是有问题的，比如编译文件的时候写死了一个需要zepto.min.js的文件，注释掉zepto.min.js后才能顺利编译通。，在试用java的中的代码时候会出现代码计算错位的问题，导致js load回来报错！

**Comment by luyongfugx** [comment]
例子的问题我看下，另外可以看看这个文章：http://my.oschina.net/luyongfugx/blog/343400  ,里面有比较详细的说明
